---
efiBootLoader: "grub"
kernelSearchPath: "/usr/lib/modules"
kernelPattern: "^vmlinuz.*"
loaderEntries:
  - "timeout 5"
  - "console-mode keep"
kernelParams: [ "quiet" ]
installEFIFallback: true
installHybridGRUB: false
