---
displaymanagers:
  - sddm
  - gdm
  - lightdm

defaultDesktopEnvironment:
  executable: "/usr/bin/startplasma-wayland"
  desktopFile: "plasma.desktop"

basicSetup: false
sysconfigSetup: false

sddm:
  configuration_file: "/etc/sddm.conf"

lightdm:
  preferred_greeters: [ "lightdm-gtk-greeter.desktop", "slick-greeter.desktop" ]
