---
efi:
  mountPoint: "/boot/efi"
  recommendedSize: 512MiB
  minimumSize: 300MiB
  label: "EFI"

userSwapChoices:
  - none
  - small
  - suspend
  - file

drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: small
defaultPartitionTableType: gpt
defaultFileSystemType: "btrfs"
availableFileSystemTypes: [ "btrfs", "ext4", "xfs", "f2fs" ]

directoryFilesystemRestrictions:
  - directory: "/"
    allowedFilesystemTypes: [ "btrfs", "ext4", "xfs", "f2fs" ]
  - mountpoint: "efi"
    allowedFilesystemTypes: [ "fat32" ]
    onlyWhenMountpoint: true

essentialMounts: [ "live-*", "control", "ventoy" ]

lvm:
  enable: true
