---
defaultGroups:
  - name: users
    must_exist: true
    system: true
  - lp
  - video
  - network
  - storage
  - audio
  - input
  - render
  - games
  - name: wheel
    must_exist: false
    system: true

sudoersGroup: wheel
sudoersConfigureWithGroup: false
setRootPassword: true
doReusePassword: true
displayAutologin: true
doAutologin: false

passwordRequirements:
  minLength: 8
  maxLength: 64

allowWeakPasswords: false
allowWeakPasswordsDefault: false

user:
  shell: /bin/bash
  forbidden_names: [ root, nobody, daemon ]
  home_permissions: "o700"

hostname:
  location: EtcFile
  writeHostsFile: true
  template: "livio"

allowActiveDirectory: false
