---
showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true
showDonateUrl: false

requirements:
  requiredStorage: 40
  requiredRam: 4.0
  internetCheckUrl:
    - https://archlinux.org
    - https://www.kernel.org
  check:
    - storage
    - ram
    - power
    - internet
    - root
    - screen
  required:
    - storage
    - ram
    - internet
