---
modules-search: [ local ]

instances:
  - id: bootstrap
    module: shellprocess
    config: livio-bootstrap.conf
  - id: online
    module: packages
    config: packages.conf
  - id: kernel
    module: packagechooser
    config: packagechooser_kernel.conf
  - id: desktop
    module: packagechooser
    config: packagechooser_desktop.conf
  - id: gpu
    module: packagechooser
    config: packagechooser_gpu.conf

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - packagechooser@kernel
      - packagechooser@desktop
      - packagechooser@gpu
      - netinstall
      - users
      - summary
  - exec:
      - partition
      - mount
      - shellprocess@bootstrap
      - packages@online
      - machineid
      - locale
      - keyboard
      - localecfg
      - luksbootkeyfile
      - luksopenswaphookcfg
      - fstab
      - initcpiocfg
      - initcpio
      - users
      - networkcfg
      - displaymanager
      - hwclock
      - grubcfg
      - bootloader
      - services-systemd
      - umount
  - show:
      - finished

branding: livio
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: true
quit-at-end: false
